export enum XfsMessage {

    OPEN_COMPLETE = 1,
    CLOSE_COMPLETE = 2,
    LOCK_COMPLETE = 3,
    UNLOCK_COMPLETE = 4,
    REGISTER_COMPLETE = 5,
    DEREGISTER_COMPLETE = 6,
    GETINFO_COMPLETE = 7,
    EXECUTE_COMPLETE = 8,

    EXECUTE_EVENT = 20,
    SERVICE_EVENT = 21,
    USER_EVENT = 22,
    SYSTEM_EVENT = 23,

    TIMER_EVENT = 100,

}